### ISSUE TITLE
it's ok to write data to local table. but error writing to distributed table

### ISSUE THREAD

**Issue by Tasselmi** [blynkkk/clickhouse4j#49]
error code
```
scala> :paste
// Entering paste mode (ctrl-D to finish)

      lv1.repartition(30)
          .write
          .mode(SaveMode.Append)
          .format("jdbc")
          .option("url", ckUrlDa)
          .option("driver", driverClass4j)
          //.option("numPartitions", "1")
          .option("dbtable", "t_md_page_path_di_rep")
          .option("user", userMe)
          .option("password", passwordMe)
          .option("fetchsize", fetchSize)
          .option("batchsize", batchSize)
          .save()

// Exiting paste mode, now interpreting.


scala> :paste
// Entering paste mode (ctrl-D to finish)

      lv1.repartition(30)
          .write
          .mode(SaveMode.Append)
          .format("jdbc")
          .option("url", ckUrlDa)
          .option("driver", driverClass4j)
          //.option("numPartitions", "1")
          .option("dbtable", "t_md_page_path_di_dis")
          .option("user", userMe)
          .option("password", passwordMe)
          .option("fetchsize", fetchSize)
          .option("batchsize", batchSize)
          .save()

// Exiting paste mode, now interpreting.

cc.blynk.clickhouse.except.ClickHouseException: ClickHouse exception, code: 62, host: null, port: 0; Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 159: NOT NULL, "node_depth" INTEGER NOT NULL, "page_id_lv1" TEXT , "page_id_lv2" TEXT NOT NULL, "page_id_lv3" TEXT NOT NULL, "page_id_lv4" TEXT NOT NULL, "page_id_lv. Expected one of: DEFAULT, MATERIALIZED, ALIAS, COMMENT, CODEC, TTL, token, ClosingRoundBracket, Comma (version 19.15.3.6 (official build))

  at cc.blynk.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:61)
  at cc.blynk.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:31)
  at cc.blynk.clickhouse.http.DefaultHttpConnector.checkForErrorAndThrow(DefaultHttpConnector.java:296)
  at cc.blynk.clickhouse.http.DefaultHttpConnector.sendPostRequest(DefaultHttpConnector.java:175)
  at cc.blynk.clickhouse.http.DefaultHttpConnector.post(DefaultHttpConnector.java:62)
  at cc.blynk.clickhouse.http.DefaultHttpConnector.post(DefaultHttpConnector.java:74)
  at cc.blynk.clickhouse.ClickHouseStatementImpl.sendRequest(ClickHouseStatementImpl.java:674)
  at cc.blynk.clickhouse.ClickHouseStatementImpl.executeUpdate(ClickHouseStatementImpl.java:198)
  at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.createTable(JdbcUtils.scala:692)
  at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:89)
  at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:518)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:218)
  ... 59 elided
Caused by: java.lang.Throwable: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 159: NOT NULL, "node_depth" INTEGER NOT NULL, "page_id_lv1" TEXT , "page_id_lv2" TEXT NOT NULL, "page_id_lv3" TEXT NOT NULL, "page_id_lv4" TEXT NOT NULL, "page_id_lv. Expected one of: DEFAULT, MATERIALIZED, ALIAS, COMMENT, CODEC, TTL, token, ClosingRoundBracket, Comma (version 19.15.3.6 (official build))

  at cc.blynk.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:56)
  ... 70 more
```

**Comment by doom369** [comment]
Are you sure local and distributed tables are the same?

**Comment by Tasselmi** [comment]
> Are you sure local and distributed tables are the same?

I am sure.

```
CREATE TABLE IF NOT EXISTS ads_ubs.t_md_page_path_di_dis ON CLUSTER ubs_1st AS ads_ubs.t_md_page_path_di_rep
ENGINE = Distributed(ubs_1st, ads_ubs, t_md_page_path_di_rep, rand());;
```

**Comment by Tasselmi** [comment]
> Are you sure local and distributed tables are the same?

I think i found why. thanks

**Comment by nblagodarnyi** [comment]
> > Are you sure local and distributed tables are the same?
> 
> I think i found why. thanks

Very helpful, thank you. What was the root cause and the solution?
